### ISSUE TITLE
Crash on "Decks" screen

### ISSUE THREAD

**Issue by telotortium** [trgkanki/remaining_time#33]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.7
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-12-11 23:25:53
Add-ons possibly involved: ⁨Remaining time for Anki 21⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 37, in cmd
  File "aqt/webview.py", line 123, in _onCmd
  File "aqt/webview.py", line 541, in _onBridgeCmd
  File "aqt/gui_hooks.py", line 2959, in __call__
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1508357010/utils/JSCallable.py", line 29, in _onBridgeMessage
    ret = func(*argList)
  File "/Users/rmi1/Library/Application Support/Anki2/addons21/1508357010/jsapi/getCurrentCardId.py", line 8, in getCurrentCardId
    return reviewer.card.id
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by phu54321** [comment]
ETA today
