### ISSUE TITLE
Hi, Still not working :(

### ISSUE THREAD

**Issue by doireallyhavetohaveausername** [trgkanki/remaining_time#81]
# Bug report
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22635

When loading remaining_time:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\remaining_time\__init__.py", line 24, in <module>
    from .utils import openChangelog
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\remaining_time\utils\openChangelog.py", line 44, in <module>
    showChangelogOnUpdate()
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\remaining_time\utils\openChangelog.py", line 40, in showChangelogOnUpdate
    dlg = MiniBrowser(None, "CHANGELOG.html")
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\remaining_time\utils\MiniBrowser.py", line 41, in __init__
    self.setWindowFlags(Qt.Window)
AttributeError: type object 'Qt' has no attribute 'Window'

## Describe the bug

> A clear and concise description of what the bug is.

## Reproduction step

> Steps to reproduce the behavior:

## Expected behavior

> A clear and concise description of what you expected to happen.

## Actual behavior

> If applicable, add screenshots to help explain your problem.

## Anki/OS versions

- OS: *[ex: macOS Catalina, Windows 10, Ubuntu 18.04]*
- Anki version *[ex: 2.1.23]*

## Additional context

> Add any other context about the problem here.

**Comment by phu54321** [comment]
Fill the templates :)

**Comment by phu54321** [comment]
Resolved on recent updates :)
