### ISSUE TITLE
Addon shows an error after opening Anki and does not work

### ISSUE THREAD

**Issue by LucienReyes** [trgkanki/remaining_time#84]
# Bug report

## Addon doesn't work.  

> Shows an error after opening Anki, inspite of implementing AuroraWright's comment at https://github.com/trgkanki/remaining_time/issues/78

## Reproduction step

> Steps to reproduce the behavior:

1. Open Anki
2. See error 
3. Addon doesn't work

## Expected behavior

> No error. Addon working.

## Anki/OS versions

- OS: Linux Mint 21.1
- AnkiVersion ⁨24.06.3 (d678e393)⁩
- Python 3.9.18 Qt 6.6.2 PyQt 6.6.1

## Additional context

> Implemented AuroraWright's comment at https://github.com/trgkanki/remaining_time/issues/78
> Doesn't change anything

## Debug Info

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Linux-5.15.0-72-generic-x86_64-with-glibc2.35

Traceback (most recent call last):
  File "aqt.progress", line 119, in handler
  File "aqt.main", line 219, in on_window_init
  File "aqt.main", line 318, in setupProfile
  File "aqt.main", line 530, in loadProfile
  File "_aqt.hooks", line 4107, in __call__
  File "anki.hooks", line 34, in runHook
  File "/home/lucien/.local/share/Anki2/addons21/1508357010/mobileSupport/modelModifier.py", line 48, in registerMobileScript
    updateModels(col, mode)
  File "/home/lucien/.local/share/Anki2/addons21/1508357010/mobileSupport/modelModifier.py", line 84, in updateModels
    models.save(model)
  File "anki.models", line 573, in save
  File "anki.models", line 556, in update
  File "anki._backend_generated", line 1107, in add_or_update_notetype
  File "anki._backend", line 171, in _run_command
anki.errors.CardTypeError: Card template ⁨2⁩ in notetype '⁨Basic (and reversed card)-ffde5⁩' has a problem.<br>The front side is identical to card template ⁨1⁩.

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Advanced Browser ['874215009', 2023-10-21T20:04, 'None', '']
Advanced Review Bottom Bar ['1136455830', 2024-02-05T00:08, 'None', mod]
Anki Habitica for 21 ['1758045507', 2023-12-16T18:03, 'None', '']
Ankicord - Discord Rich Presence ['1828536813', 2023-08-16T21:23, 'None', '']
Button Colours Good Again ['2494384865', 2022-09-27T15:48, 'None', '']
Countdown To Events and Exams ['1143540799', 2022-06-27T17:20, 'None', '']
Custom Background Image and Gear Icon ['1210908941', 2023-04-19T06:49, 'None', mod]
Customize Keyboard Shortcuts ['24411424', 2023-11-01T14:47, 'None', mod]
Fastbar- with nightmode support ['46611790', 2023-06-27T17:17, 'None', mod]
Mini Format Pack ['295889520', 2023-11-02T23:30, 'None', '']
Puppy Reinforcement ['1722658993', 2023-11-16T18:29, 'None', mod]
ReColor ['688199788', 2024-03-03T07:15, '3.0', mod]
Remaining time for Anki 21 ['1508357010', 2024-04-16T07:45, '24.4.16i24', '']
Reset Review Stats ['742319784', 2021-06-05T15:13, 'None', '']
Reset review log ['1345711295', 2021-06-05T18:08, 'None', '']
Review Heatmap ['1771074083', 2022-07-23T13:04, 'None', '']
Symbols As You Type ['2040501954', 2024-01-20T11:12, 'None', '']

===IDs of active AnkiWeb add-ons===
1136455830 1143540799 1210908941 1345711295 1508357010 1722658993 1758045507 1771074083 1828536813 2040501954 24411424 2494384865 295889520 46611790 688199788 742319784 874215009

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS Official  Medical School Step  Shelf Study Resource ['1044112126', 2023-11-14T17:17, 'None', '']
AddonBackup ['162231225', 2019-01-16T13:23, 'None', '']
Anki Leaderboard - Compete with friends to boost motivation Fork by Shige ['175794613', 2024-07-30T07:42, 'None', mod]
AnkiCollab - The free collaboration Platform ['1957538407', 2024-07-02T17:37, 'None', mod]
AnkiConnect ['2055492159', 2024-07-26T10:25, 'None', mod]
AnkiCraft ['368161874', 2024-05-25T06:49, 'None', '']
AnkiDiscord - Discord integration for Anki ['1133851639', 2020-01-14T07:23, 'None', '']
AnkiHub ['1322529746', 2024-07-09T22:56, 'None', mod]
AwesomeTTS - Add speech to your flashcards ['1436550454', 2024-06-01T19:35, 'None', '']
Basic Printing Support ['1025789669', 2023-10-19T08:27, 'None', '']
Enhance main window ['877182321', 2023-10-23T01:58, 'None', '']
Exam Notifier ['236593452', 2023-01-19T22:42, 'None', '']
Export Deck to HTML and Print to PDF ['266464821', 2022-05-25T10:53, 'None', '']
Field AutoComplete ['511710206', 2024-07-20T19:37, 'None', '']
Picmonic Anki Add-On ['40737180', 2024-01-24T21:32, 'None', mod]
Reset Card Scheduling ['300884351', 2021-06-05T18:08, 'None', '']
Searching PDF Reading  Note-Taking in Add Dialog ['1781298089', 2022-08-15T12:52, 'None', mod]
Simple Timer and Stopwatch Fixed by Shige ['2041168053', 2024-04-08T16:27, 'None', '']
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T16:54, 'None', mod]
Sync Learned to TickTick ['240836168', 2024-03-23T01:04, 'None', mod]
True Retention ['613684242', 2017-11-20T02:13, 'None', '']
Unstable See Description Pull from Duolingo ['557761805', 2023-03-25T00:47, 'None', '']

**Comment by phu54321** [comment]
Current ankiweb version is compatible w/ latest Anki as I know of. (26.05) So closing this.
